<?php

/*
 * Relato curado del contrato observado. La procedencia de cada afirmación
 * está en docs/Docs_API/vittles/FIX_API_DOCS.md; esta página no sondea el POS.
 */
return [
    'steps' => [
        'auth' => [
            'label' => 'Autenticación',
            'title' => 'El token no dura lo documentado.',
            'official' => 'API_DOCS.md promete expires_in: 3600 y una hora de vigencia.',
            'official_code' => '{ "access_token": "…", "expires_in": 3600 }',
            'observed' => 'La respuesta HTTP trae expires: 90 y no incluye expires_in. El vencimiento efectivo de 90 segundos también aparece en TOKEN_TTL_SEC del mock.',
            'observed_code' => '{ "access_token": "[OCULTO]", "token_type": "bearer", "expires": 90 }',
            'impact' => 'Un cliente que lea solo expires_in no puede programar correctamente la renovación y terminaría consultando con un token vencido.',
            'decision' => 'VittlesClient lee expires, guarda el token solo en memoria y lo renueva antes del vencimiento.',
            'implementation' => 'VittlesClient::authenticate()',
            'claim' => 'El auditor tomó el nombre del campo y la duración del ejemplo de API_DOCS.md.',
            'probe' => 'Envió POST /oauth/token al mock y examinó el JSON HTTP 200, omitiendo el bearer al documentarlo.',
            'difference' => 'Comparó las claves: apareció expires=90; expires_in no apareció.',
            'confirmation' => 'Revisó TOKEN_TTL_SEC y do_POST en mock_server.py y documentó el contrato corregido.',
            'evidence' => 'Campo de respuesta observado por HTTP. Vencimiento efectivo derivado del código; no se esperaron 90 segundos para probarlo.',
            'source' => 'FIX_API_DOCS.md → POST /oauth/token',
        ],
        'locations' => [
            'label' => 'Locations',
            'title' => 'La primera respuesta no trae todas las sedes.',
            'official' => 'API_DOCS.md afirma que GET /v1/locations devuelve todas las locations.',
            'official_code' => 'GET /v1/locations → data: [todas las sedes]',
            'observed' => 'El mock entrega páginas de 2, 2 y 1 sedes. Las dos primeras incluyen next_cursor; hay cinco sedes en total.',
            'observed_code' => '{ "data": [2 sedes], "next_cursor": "2" }',
            'impact' => 'Si se procesa solo la primera página, tres sedes y sus menús quedan fuera de la integración.',
            'decision' => 'CatalogService sigue únicamente los cursores recibidos, detecta ciclos y consulta el menú de cada sede encontrada.',
            'implementation' => 'CatalogService::load()',
            'claim' => 'El auditor convirtió «Returns every location» en una hipótesis comprobable.',
            'probe' => 'Consultó GET /v1/locations y repitió GET con los cursores 2 y 4 devueltos por el servidor.',
            'difference' => 'Contó las respuestas 2/2/1 y encontró un campo de paginación ausente en la guía.',
            'confirmation' => 'Contrastó do_GET del mock y dejó un test de integración que espera cinco sedes y cinco intentos de menú.',
            'evidence' => 'Tres respuestas GET observadas directamente; total de cinco sedes comprobado.',
            'source' => 'FIX_API_DOCS.md → GET /v1/locations',
        ],
        'menus' => [
            'label' => 'Menús',
            'title' => 'El menú usa otro nombre y otros tipos.',
            'official' => 'La guía muestra menu_items, price decimal y available booleano.',
            'official_code' => '{ "menu_items": [{ "price": 15.50, "available": true }] }',
            'observed' => 'El GET devuelve menuItems. Algunos precios son strings numéricos y available puede ser 0/1. La sede inactiva loc_1004 responde 403 al pedir el menú.',
            'observed_code' => '{ "menuItems": [{ "price": "8.25", "available": 1 }] }',
            'impact' => 'Un cliente literal no encuentra los productos o interpreta mal su disponibilidad. Tampoco debe tratar un 403 como menú vacío.',
            'decision' => 'CatalogService normaliza los tipos observados, conserva el estado de error por sede y falla si el formato cambia de forma inesperada.',
            'implementation' => 'CatalogService::load() / normalizeItem()',
            'claim' => 'El auditor tomó el esquema de menú y la ausencia de casos para sedes inactivas de API_DOCS.md.',
            'probe' => 'Consultó el menú de loc_1001 y el de la sede inactiva loc_1004, comparando status y cuerpo.',
            'difference' => 'Encontró menuItems, variantes de tipos y HTTP 403 para la sede inactiva.',
            'confirmation' => 'Revisó MENUS y do_GET en mock_server.py; las pruebas cubren precio string y producto no disponible.',
            'evidence' => 'Campo, tipos y 403 observados por HTTP. El 500 aleatorio de menú también consta en una traza local.',
            'source' => 'FIX_API_DOCS.md → GET /v1/locations/{location_id}/menu',
        ],
        'order' => [
            'label' => 'Orden',
            'title' => 'HTTP 200 también puede significar rechazo.',
            'official' => 'La documentación no pide X-Vittles-Location y dice que un payload inválido devuelve HTTP 400.',
            'official_code' => 'POST /v1/orders + JSON documentado',
            'observed' => 'Sin X-Vittles-Location, el mock responde HTTP 200 con status REJECTED y reason: missing location context.',
            'observed_code' => 'HTTP 200 · { "status": "REJECTED", "reason": "missing location context" }',
            'impact' => 'Mirar únicamente el status HTTP podría presentar una orden rechazada como creada, con un comprobante falso.',
            'decision' => 'VittlesClient envía el header de sede y OrderService exige status ACCEPTED, ID, referencia y total válidos.',
            'implementation' => 'VittlesClient::createOrder() / OrderService::validateOrder()',
            'claim' => 'El auditor contrastó el ejemplo de POST y la tabla de errores de API_DOCS.md.',
            'probe' => 'Envió un POST de rechazo controlado sin el header; no creó una compra.',
            'difference' => 'Observó HTTP 200/REJECTED, una combinación no descrita por la documentación.',
            'confirmation' => 'Revisó do_POST y añadió un test que impide informar CREATED ante 200/REJECTED.',
            'evidence' => 'POST rechazado observado directamente. La vista no envía POST al abrirse.',
            'source' => 'FIX_API_DOCS.md → POST /v1/orders',
        ],
        'idempotency' => [
            'label' => 'Idempotencia',
            'title' => 'client_ref no evita duplicados en Vittles.',
            'official' => 'La guía promete que repetir un POST con el mismo client_ref devuelve la orden original.',
            'official_code' => 'POST(ref A) → orden X · POST(ref A) → orden X',
            'observed' => 'Dos POST aceptados con la misma referencia produjeron dos órdenes. El endpoint GET /v1/orders?client_ref=... permite buscarlas, pero no hace atómica la creación.',
            'observed_code' => 'POST(ref A) → orden X · POST(ref A) → orden Y',
            'impact' => 'Reintentar un POST después de un timeout podría cobrar o registrar una compra duplicada.',
            'decision' => 'OrderService genera una referencia estable, busca antes de crear y reconcilia respuestas inciertas sin reenviar el POST. No promete exactly once distribuido.',
            'implementation' => 'OrderService::findByReference() / reconcileUnknown()',
            'claim' => 'El auditor aisló la afirmación de idempotencia de client_ref en API_DOCS.md.',
            'probe' => 'Comparó dos POST válidos con la misma referencia de una prueba previa y consultó el GET de búsqueda.',
            'difference' => 'Los POST generaron IDs distintos; la búsqueda devolvió la lista de coincidencias.',
            'confirmation' => 'Revisó do_POST, que no consulta duplicados, y verificó con tests que dos ejecuciones de nuestra integración hagan un solo POST.',
            'evidence' => 'Duplicado secuencial observado previamente. La carrera entre clientes se deduce del código; esta pantalla no la reproduce.',
            'source' => 'FIX_API_DOCS.md → Idempotencia real y GET /v1/orders?client_ref=...',
        ],
    ],
];
